version: '3.7'

services:
  app:
    build: .docker/app/
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  nginx:
    build: .docker/nginx/
    ports:
      - 8000:80
    networks:
      - app-network
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 33061:3306
  node:
    image: node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

volumes:
  mysql-volume:
networks:
  app-network: