version: '3.7'

services:
  app:
    build: .docker/app/
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  nginx:
    build: .docker/nginx/
    ports:
      - 8000:80
    networks:
      - app-network
    volumes:
      - .:/var/www/html

networks:
  app-network: